INSERT INTO mpa VALUES(1, 'G');
INSERT INTO mpa VALUES(2, 'PG');
INSERT INTO mpa VALUES(3, 'PG-13');
INSERT INTO mpa VALUES(4, 'R');
INSERT INTO mpa VALUES(5, 'NC-17');

INSERT INTO genres VALUES(1, 'Комедия');
INSERT INTO genres VALUES(2, 'Драма');
INSERT INTO genres VALUES(3, 'Мультфильм');
INSERT INTO genres VALUES(4, STRINGTOUTF8('Триллер'));
INSERT INTO genres VALUES(5, STRINGTOUTF8('Документальный'));
INSERT INTO genres VALUES(6, STRINGTOUTF8('Боевик'));
